/**
* Copyright 2011 Facebook, Inc.
*
* You are hereby granted a non-exclusive, worldwide, royalty-free license to
* use, copy, modify, and distribute this software in source code or binary
* form for use in connection with the web services and APIs provided by
* Facebook.
*
* As with any software that integrates with the Facebook platform, your use
* of this software is subject to the Facebook Developer Principles and
* Policies [http://developers.facebook.com/policy/]. This copyright notice
* shall be included in all copies or substantial portions of the software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*
*
* This file is automatically generated by
* scripts/admanager/powereditor/generate_js/locale.php
* do not modify
*
* @nolint
*/

var locales =
{"1":"Catalan","2":"Czech","3":"Welsh","4":"Danish","5":"German","6":"English (US)","7":"Spanish (Spain)","8":"Finnish","9":"French (France)","10":"Italian","11":"Japanese","12":"Korean","13":"Norwegian (bokmal)","14":"Dutch","15":"Polish","16":"Portuguese (Brazil)","17":"Russian","18":"Swedish","19":"Turkish","20":"Simplified Chinese (China)","21":"Traditional Chinese (Hong Kong)","22":"Traditional Chinese (Taiwan)","23":"Spanish","24":"English (UK)","25":"Indonesian","26":"Filipino","27":"Vietnamese","28":"Arabic","29":"Hebrew","30":"Hungarian","31":"Portuguese (Portugal)","32":"Romanian","33":"Slovak","34":"Slovenian","35":"Thai","36":"Afrikaans","37":"Bulgarian","38":"Croatian","39":"Greek","40":"Lithuanian","41":"Malay","42":"Serbian","44":"French (Canada)","45":"Bengali","46":"Hindi","47":"Punjabi","48":"Tamil","49":"Telugu","50":"Malayalam","51":"English (Upside Down)"};

exports.locales = locales;

